server:
  port : 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/books_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: book_admin
    password: password@123

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect